version: "3.8"

services:
  frigate:
    devices:
      - /dev/dri:/dev/dri # 用于GPU硬件加速
      - /dev/dma_heap # RockChip DMA 堆
      - /dev/rga # RockChip RGA
      - /dev/mpp_service # RockChip MPP 服务
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    volumes:
      - /sys/:/sys/:ro
